### PR TITLE
Expose default client configuration

### PR DESCRIPTION
**Pull request by skycoop**
I moved the default config to a class variable so that users could access it. I personally need this so that I can get a list of the expected configuration values so that I can pull them from the Flask application configuration.

### CODE REVIEW

**Comment by skycoop** [comment]
I didn't add any tests since the existing tests seemed to cover the configuration well. Please let me know if I need to add any tests or documentation

**Comment by dgilland** [comment]
Thanks for the PR!

I need to ponder the implementation some, though. My main concern with having the config as a class variable is that it opens up the following bug:

```python
class MyClient(SQLClient): pass

MyClient.DEFAULT_CONFIG['foo'] = 'bar'
SQLClient.DEFAULT_CONFIG['foo'] == 'bar'
```

and any other modification to `SQLClient.DEFAULT_CONFIG` or its subclasses. Obviously, one shouldn't do that but it would be nice to prevent it from happening in the first place while still allowing static access to the default config and the ability to override the default config in a subclass.

**Comment by dgilland** [comment]
Thanks for the PR!

I need to ponder the implementation some, though. My main concern with having the config as a class variable is that it opens up the following bug:

```python
class MyClient(SQLClient): pass

MyClient.DEFAULT_CONFIG['foo'] = 'bar'
SQLClient.DEFAULT_CONFIG['foo'] == 'bar'
```

and any other modification to `SQLClient.DEFAULT_CONFIG` or its subclasses. Obviously, one shouldn't do that but it would be nice to prevent it from happening in the first place while still allowing static access to the default config and the ability to override the default config in a subclass.

**Comment by dgilland** [comment]
Thanks for the PR!

I need to ponder the implementation some, though. My main concern with having the config as a class variable is that it opens up the following bug:

```python
class MyClient(SQLClient): pass

MyClient.DEFAULT_CONFIG['foo'] = 'bar'
SQLClient.DEFAULT_CONFIG['foo'] == 'bar'
```

and any other modification to `SQLClient.DEFAULT_CONFIG` or its subclasses. Obviously, one shouldn't do that but it would be nice to prevent it from happening in the first place while still allowing static access to the default config and the ability to override the default config in a subclass.

**Comment by dgilland** [comment]
Thanks for the PR!

I need to ponder the implementation some, though. My main concern with having the config as a class variable is that it opens up the following bug:

```python
class MyClient(SQLClient): pass

MyClient.DEFAULT_CONFIG['foo'] = 'bar'
SQLClient.DEFAULT_CONFIG['foo'] == 'bar'
```

and any other modification to `SQLClient.DEFAULT_CONFIG` or its subclasses. Obviously, one shouldn't do that but it would be nice to prevent it from happening in the first place while still allowing static access to the default config and the ability to override the default config in a subclass.

**Comment by skycoop** [comment]
Oh.... That's a sneaky problem. `frozendict` never became a built-in, and we don't have access to `MappingProxyType` in Python 2. The solutions I can think of right now are:
- Add `frozendict` or something similar as a dependency
- Use a `namedtuple`
- Hand roll an immutable dictionary (this is what Flask/werkzeug opted to do, [implementation](https://github.com/pallets/werkzeug/blob/73683a2ee741288c18751a4f739b9758a9e18a55/werkzeug/datastructures.py#L1542))
- Use a `staticmethod` or `classmethod` getter (i.e. `self.get_default_config()`)

**Comment by dgilland** [comment]
I think the most straight-forward thing would be to just implement a `fronzendict` class like https://github.com/slezica/python-frozendict/blob/master/frozendict/__init__.py#L16-L52.

**Comment by skycoop** [comment]
Sounds good to me. I can take a crack at the implementation.

**Comment by dgilland** [comment]
That's fine but if you don't have time then I can go ahead and merge this PR and then add the frozendict implementation myself.

**Comment by skycoop** [comment]
Sorry, I completely forgot about this. Been pretty busy, but I have some downtime, so I'll work on it right now

**Comment by skycoop** [comment]
Just pushed the implementation. It's pretty similar to the one you linked, but I dropped out methods that didn't seem useful (we never need a hash for the default config), and preferred proxying to the dict implementation of the methods

**Comment by dgilland** [comment]
Thanks again for the PR! 👍

**Comment by skycoop** [comment]
No problem :smiley:

**Pull request merged**
